"""
Shared feature extraction for both detectors.

Both the rule-based and the ML detector score the same units - Modbus
*request* frames (the response direction is generated by the PLC, not by a
client, so it can't carry an attack) - and read them from the same capture
CSVs, so their comparison is apples-to-apples.

Provides:
  load_requests(csv)      -> tidy per-request DataFrame (typed, time-sorted,
                             with per-connection inter-arrival time)
  build_feature_matrix(df)-> numeric ndarray for the ML detector

Kept deliberately small and explicit: the exact columns the ML model sees are
easy to read off here, which matters for writing up the methodology.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

# The numeric columns the ML anomaly detector is trained on. Chosen to match
# the proposal: function-code, register address/value, request size, and
# inter-packet timing per connection.
ML_FEATURE_COLUMNS = ["function_code", "address", "value0", "count", "inter_arrival"]


def _first_value(values_field: str) -> float:
    """First integer in the space-separated `values` column (0 for reads,
    which carry no written value)."""
    if isinstance(values_field, str) and values_field.strip():
        try:
            return float(values_field.split()[0])
        except (ValueError, IndexError):
            return 0.0
    return 0.0


def load_requests(csv_path: str) -> pd.DataFrame:
    """Load a capture/labeled CSV and return only request frames, typed and
    time-sorted, with derived per-connection features."""
    df = pd.read_csv(csv_path)
    df = df[df["direction"] == "req"].copy()

    # Numeric coercions; reads leave address/count/value blank -> 0.
    for col in ["function_code", "address", "count", "transaction_id", "client_port"]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    df["value0"] = df["values"].apply(_first_value)
    df["wall_time"] = pd.to_numeric(df["wall_time"], errors="coerce")

    df = df.sort_values("wall_time").reset_index(drop=True)

    # Inter-arrival time within each TCP connection (client_port). The first
    # request on a connection has no predecessor -> 0.
    df["inter_arrival"] = (
        df.groupby("client_port")["wall_time"].diff().fillna(0.0)
    )

    if "is_attack" in df.columns:
        df["is_attack"] = pd.to_numeric(df["is_attack"], errors="coerce").fillna(0).astype(int)

    return df


def build_feature_matrix(df: pd.DataFrame) -> np.ndarray:
    """Numeric feature matrix (rows = requests) for the ML detector."""
    return df[ML_FEATURE_COLUMNS].to_numpy(dtype=float)
